/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.servicio.CuentaServicio;
import controlador.utilidades.Sesion;
import vista.utilidades.UtilidadesComponente;

/**
 *
 * @author Jean Pierre
 */
public class FRMLogin extends javax.swing.JDialog {

    /**
     * Creates new form FRMLogin
     */
    public FRMLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private void inicioSesion() {
        if (!UtilidadesComponente.mostrarError(txt_usuario, "Falta este campo", 'r')
                && !UtilidadesComponente.mostrarError(txt_pass, "Falta este campo", 'r')) {
            Sesion.setCuenta(new CuentaServicio().inicioSesion(txt_usuario.getText(),
                    new String(txt_pass.getPassword())));
            if (Sesion.getCuenta() != null) {
                new FRMPrincipal().setVisible(true);
                dispose();
            } else {
                UtilidadesComponente
                        .mensajeError("Error de acceso", "Hubo un error con sus credenciales");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelCurves2 = new org.edisoncor.gui.panel.PanelCurves();
        txt_usuario = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        txt_pass = new org.edisoncor.gui.passwordField.PasswordFieldRoundBackground();
        btn_login1 = new org.edisoncor.gui.button.ButtonColoredAction();
        btn_registrar = new org.edisoncor.gui.button.ButtonColoredAction();
        btn_salir = new org.edisoncor.gui.button.ButtonColoredAction();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        labelCustom1 = new org.edisoncor.gui.label.LabelCustom();
        labelCustom2 = new org.edisoncor.gui.label.LabelCustom();
        labelCustom3 = new org.edisoncor.gui.label.LabelCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        getContentPane().setLayout(null);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/fondo.jpg"))); // NOI18N
        panelImage1.setLayout(null);

        panelCurves2.setLayout(null);

        txt_usuario.setBackground(new java.awt.Color(0, 0, 0));
        txt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_usuario.setColorDeTextoBackground(new java.awt.Color(204, 204, 204));
        txt_usuario.setDescripcion("ingrese usuario aquí");
        txt_usuario.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        panelCurves2.add(txt_usuario);
        txt_usuario.setBounds(60, 210, 300, 30);

        txt_pass.setBackground(new java.awt.Color(0, 0, 0));
        txt_pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass.setColorDeTextoBackground(new java.awt.Color(204, 204, 204));
        txt_pass.setDescripcion("ingrese contraseña aquí");
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        panelCurves2.add(txt_pass);
        txt_pass.setBounds(60, 290, 300, 30);

        btn_login1.setBackground(new java.awt.Color(0, 51, 0));
        btn_login1.setText("Login");
        btn_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login1ActionPerformed(evt);
            }
        });
        panelCurves2.add(btn_login1);
        btn_login1.setBounds(30, 350, 116, 30);

        btn_registrar.setBackground(new java.awt.Color(0, 51, 0));
        btn_registrar.setText("Registrar.");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        panelCurves2.add(btn_registrar);
        btn_registrar.setBounds(150, 350, 116, 30);

        btn_salir.setBackground(new java.awt.Color(0, 51, 0));
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panelCurves2.add(btn_salir);
        btn_salir.setBounds(270, 350, 116, 30);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/user2.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        panelCurves2.add(panelImage2);
        panelImage2.setBounds(320, 80, 80, 80);

        labelCustom1.setBackground(new java.awt.Color(0, 0, 0));
        labelCustom1.setText("LOGIN");
        labelCustom1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        panelCurves2.add(labelCustom1);
        labelCustom1.setBounds(0, 30, 410, 40);

        labelCustom2.setBackground(new java.awt.Color(255, 255, 255));
        labelCustom2.setForeground(new java.awt.Color(0, 0, 0));
        labelCustom2.setText("Contraseña");
        labelCustom2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        panelCurves2.add(labelCustom2);
        labelCustom2.setBounds(60, 260, 100, 20);

        labelCustom3.setBackground(new java.awt.Color(255, 255, 255));
        labelCustom3.setForeground(new java.awt.Color(0, 0, 0));
        labelCustom3.setText("Usuario");
        labelCustom3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        panelCurves2.add(labelCustom3);
        labelCustom3.setBounds(55, 177, 100, 20);

        panelImage1.add(panelCurves2);
        panelCurves2.setBounds(0, 0, 410, 460);

        getContentPane().add(panelImage1);
        panelImage1.setBounds(0, 0, 410, 460);

        setSize(new java.awt.Dimension(425, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void btn_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login1ActionPerformed
        inicioSesion();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_login1ActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        new FRMRegistro(null, true).setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRMLogin dialog = new FRMLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonColoredAction btn_login1;
    private org.edisoncor.gui.button.ButtonColoredAction btn_registrar;
    private org.edisoncor.gui.button.ButtonColoredAction btn_salir;
    private org.edisoncor.gui.label.LabelCustom labelCustom1;
    private org.edisoncor.gui.label.LabelCustom labelCustom2;
    private org.edisoncor.gui.label.LabelCustom labelCustom3;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves2;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.passwordField.PasswordFieldRoundBackground txt_pass;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txt_usuario;
    // End of variables declaration//GEN-END:variables
}
