/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.servicio.CuentaServicio;
import controlador.servicio.PersonaServicio;
import controlador.servicio.RolServicio;
import controlador.utilidades.Utilidades;
import java.util.UUID;
import vista.utilidades.UtilidadesComponente;

/**
 *
 * @author Jean Pierre
 */
public class FRMRegistro extends javax.swing.JDialog {

    PersonaServicio ps = new PersonaServicio();
    CuentaServicio cs = new CuentaServicio();
    RolServicio rs = new RolServicio();
    
    
    /**
     * Creates new form FRMRegistro
     */
    public FRMRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private void cargarObjeto() {
        ps.getPersona().setCedula(txt_cedula.getText());
        ps.getPersona().setApellidos(txt_apellido.getText());
        ps.getPersona().setNombres(txt_nombre.getText());
        ps.getPersona().setTelefono(txt_tel.getText());
        ps.getPersona().setDireccion(txt_dir.getText());
        ps.getPersona().setExternal_id(UUID.randomUUID().toString());
        cs.getCuenta().setUsuario(txt_usuario.getText());
        cs.getCuenta().setClave(txt_pass.getText());
        cs.getCuenta().setPersona(ps.getPersona());
        if (rb_e.isSelected()) {
            ps.getPersona().setRol(new RolServicio().buscarRolNombre("Estudiante"));
        }else{
            ps.getPersona().setRol( new RolServicio().buscarRolNombre("Administrador"));
        }
        
    }
    
    private void guardar() {
        String mensaje = "Se requiere este campo";
        if (!UtilidadesComponente.mostrarError(txt_usuario, "Falta este dato", 'r')
                && !UtilidadesComponente.mostrarError(txt_nombre, "Falta este dato", 'r')
                && !UtilidadesComponente.mostrarError(txt_apellido, "Falta este dato", 'r')
                && !UtilidadesComponente.mostrarError(txt_cedula, "Falta este dato", 'r')
                && !UtilidadesComponente.mostrarError(txt_dir, "Falta este dato", 'r')
                && !UtilidadesComponente.mostrarError(txt_tel, "Falta este dato", 'r')
                && !UtilidadesComponente.mostrarError(txt_pass, "Falta este dato", 'r')) {
                cargarObjeto();
            if (ps.getPersona().getId() != null ) {
                if (ps.guardar()&& cs.guardar()) {
                    UtilidadesComponente.mensajeOk("Se ha modificado correctamente", "");
                    limpiar();
                } else {
                    UtilidadesComponente.mensajeError("Error", "No se pudo modificarr");
                }
            } else {
                if(Utilidades.validadorDeCedula(txt_cedula.getText())){
                    if(ps.getPersonaCedula(txt_cedula.getText()) != null){
                        UtilidadesComponente.mensajeError("Error de cédula", "cedula ya registrada");
                    }else{
                        if (ps.guardar()&& cs.guardar()) {
                            UtilidadesComponente.mensajeOk("OK", "Se ha guardado correctamente");
                            limpiar();
                        } else {
                            UtilidadesComponente.mensajeError("Error", "No se pudo guardar");
                        }   
                    }
                }else{
                    UtilidadesComponente.mensajeError("Error de cedula.", "Cedula no valida.");
                }
            }
        }
    }
    
    private void limpiar() {
        txt_apellido.setText(null);
        txt_tel.setText(null);
        txt_dir.setText(null);;
        txt_pass.setText(null);
        txt_nombre.setText(null);
        txt_tel.setText(null);
        txt_usuario.setText(null);
        txt_cedula.setText(null);
        txt_cedula.setEditable(true);
        rb_e.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_dir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JTextField();
        rb_e = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btn_cancelar = new org.edisoncor.gui.button.ButtonColoredAction();
        btn_guardar = new org.edisoncor.gui.button.ButtonColoredAction();
        btn_login1 = new org.edisoncor.gui.button.ButtonColoredAction();
        btn_salir = new org.edisoncor.gui.button.ButtonColoredAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Estudiante.");
        setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        getContentPane().setLayout(null);

        panelNice1.setBackground(new java.awt.Color(0, 0, 0));
        panelNice1.setForeground(new java.awt.Color(102, 0, 0));
        panelNice1.setLayout(null);

        panelCurves1.setLayout(null);

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Estudiante.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Georgia", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panel1.setColorPrimario(new java.awt.Color(102, 51, 0));
        panel1.setColorSecundario(new java.awt.Color(102, 51, 0));
        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/fondo.jpg"))); // NOI18N
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Teléfono.");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 100, 34));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("C.I.");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 60, 90, 34));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombres.");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, 34));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellidos.");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 100, 34));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección.");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 100, 34));
        panel1.add(txt_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 150, 30));

        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        panel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 150, 30));

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        panel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, 30));

        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyTyped(evt);
            }
        });
        panel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 150, 30));
        panel1.add(txt_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 150, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre usuario.");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 34));
        panel1.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 150, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña.");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, 34));

        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        panel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 150, 30));

        rb_e.setBackground(new java.awt.Color(255, 255, 255));
        rb_e.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        rb_e.setForeground(new java.awt.Color(255, 255, 255));
        rb_e.setText("Estudiante");
        panel1.add(rb_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 120, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 60, 30));

        panelCurves1.add(panel1);
        panel1.setBounds(20, 80, 620, 320);

        btn_cancelar.setBackground(new java.awt.Color(51, 51, 0));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        panelCurves1.add(btn_cancelar);
        btn_cancelar.setBounds(450, 410, 90, 30);

        btn_guardar.setBackground(new java.awt.Color(51, 51, 0));
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        panelCurves1.add(btn_guardar);
        btn_guardar.setBounds(250, 410, 90, 30);

        btn_login1.setBackground(new java.awt.Color(51, 51, 0));
        btn_login1.setText("Login");
        btn_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login1ActionPerformed(evt);
            }
        });
        panelCurves1.add(btn_login1);
        btn_login1.setBounds(350, 410, 90, 30);

        btn_salir.setBackground(new java.awt.Color(51, 51, 0));
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panelCurves1.add(btn_salir);
        btn_salir.setBounds(550, 410, 90, 30);

        panelNice1.add(panelCurves1);
        panelCurves1.setBounds(0, 10, 670, 530);

        getContentPane().add(panelNice1);
        panelNice1.setBounds(0, -10, 670, 540);

        setSize(new java.awt.Dimension(685, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        limpiar();           // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        guardar();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login1ActionPerformed
       new FRMLogin(null, true).setVisible(true);  
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btn_login1ActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirActionPerformed

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        char s = evt.getKeyChar();
            if((s<'a' || s>'z')&&(s<'A' || s>'Z')) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyTyped
        char s = evt.getKeyChar();
            if((s<'a' || s>'z')&&(s<'A' || s>'Z')) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRMRegistro dialog = new FRMRegistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonColoredAction btn_cancelar;
    private org.edisoncor.gui.button.ButtonColoredAction btn_guardar;
    private org.edisoncor.gui.button.ButtonColoredAction btn_login1;
    private org.edisoncor.gui.button.ButtonColoredAction btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private javax.swing.JRadioButton rb_e;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_dir;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
