/*
 * To change thms license header, choose License Headers in Project Properties.
 * To change thms template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.servicio.MateriaServicio;
import controlador.servicio.PersonaServicio;
import controlador.utilidades.Sesion;
import vista.tablas.ModeloTablaMateria;
import vista.utilidades.UtilidadesComponente;

/**
 *
 * @author Jean Pierre
 */
public class FRMRMaterias extends javax.swing.JDialog {
    
    private PersonaServicio ps = new PersonaServicio();
    private MateriaServicio ms = new  MateriaServicio();
    private ModeloTablaMateria modelo = new ModeloTablaMateria();

    /**
     * Creates new form FRMRMaterias
     */
    public FRMRMaterias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarDatosUsuario();
    }
    
    private void cargarDatosUsuario(){
        ps.fijarPersona(Sesion.getCuenta().getPersona());
        txt_nombre.setText(ps.getPersona().toString());
    }
   
    private void cargarTabla() {
       //modelo.setListaMat(ms.todos());
        modelo.setListaMat(ms.listarMateriaNombre(ps.getPersona().getId()));
        tbl_tabla.setModel(modelo);
        tbl_tabla.updateUI();
    }
    
    private void cargarObjeto() {
        ps.fijarPersona(Sesion.getCuenta().getPersona());
        ms.getMateria().setNombreMateria(txt_nomMateria.getText());
        ms.getMateria().setCreditos(Integer.parseInt(txt_creditos.getText()));
        ms.getMateria().setNombreProfesor(txt_nomProf.getText());
        ms.getMateria().setPersona(ps.getPersona());
    }
    private void cargarVista() {
        int fila = tbl_tabla.getSelectedRow();
        if(fila >= 0 ) {
            ms.fijarMateria(modelo.getListaMat().get(fila));
            txt_nomMateria.setText(ms.getMateria().getNombreMateria());
            txt_creditos.setText(String.valueOf(ms.getMateria().getCreditos()));
            txt_nomProf.setText(ms.getMateria().getNombreProfesor());        
        } else {
            UtilidadesComponente.mensajeError("Error", "Llene todoss los campos");
        }
    }
    
    private void limpiar() {
        ms.fijarMateria(null);
        cargarTabla();
        txt_nomMateria.setText("");
        txt_creditos.setText("");
        txt_nomProf.setText("");
    }
    private void guardar() {
        String mensaje = "Se requiere este campo";
        if(!UtilidadesComponente.mostrarError(txt_nomMateria, mensaje, 'r') &&
                !UtilidadesComponente.mostrarError(txt_creditos, mensaje, 'r') && 
                !UtilidadesComponente.mostrarError(txt_nomProf, mensaje, 'r')){
            cargarObjeto();
            if(ms.getMateria().getId() != null) {
                if(ms.guardar()) {
                    UtilidadesComponente.mensajeOk("Se ha modificado correctamente","Ok");
                    limpiar();
                } else {
                    UtilidadesComponente.mensajeError("Error", "No se pudo modificar");
                }
            } else {
                if(ms.guardar()) {
                    UtilidadesComponente.mensajeOk("OK", "Se ha guardado correctamente");
                    limpiar();
                } else {
                    UtilidadesComponente.mensajeError("Error", "No se pudo guardar");
                }
            }
        }
    }
    
    /**
     * Thms method ms called from within the constructor to initialize the form.
     * WARNING: Do NOT modify thms code. The content of thms method ms always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldRectIcon1 = new org.edisoncor.gui.textField.TextFieldRectIcon();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        btn_editar = new org.edisoncor.gui.button.ButtonColoredAction();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tabla = new javax.swing.JTable();
        labelCustom1 = new org.edisoncor.gui.label.LabelCustom();
        txt_nombre = new org.edisoncor.gui.textField.TextField();
        labelCustom3 = new org.edisoncor.gui.label.LabelCustom();
        btn_salir = new org.edisoncor.gui.button.ButtonColoredAction();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        txt_nomMateria = new javax.swing.JTextField();
        txt_creditos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nomProf = new javax.swing.JTextField();
        btn_guardar = new org.edisoncor.gui.button.ButtonColoredAction();
        btn_Nuevo1 = new org.edisoncor.gui.button.ButtonColoredAction();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();

        textFieldRectIcon1.setText("textFieldRectIcon1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Materias");
        setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        getContentPane().setLayout(null);

        panelNice1.setBackground(new java.awt.Color(0, 0, 0));
        panelNice1.setForeground(new java.awt.Color(102, 0, 0));
        panelNice1.setLayout(null);

        panelCurves1.setLayout(null);

        btn_editar.setBackground(new java.awt.Color(0, 51, 0));
        btn_editar.setText("Editar");
        btn_editar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        panelCurves1.add(btn_editar);
        btn_editar.setBounds(490, 430, 116, 30);

        tbl_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_tabla);

        panelCurves1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 430, 452, 90);

        labelCustom1.setBackground(new java.awt.Color(0, 0, 0));
        labelCustom1.setText("Usuario");
        panelCurves1.add(labelCustom1);
        labelCustom1.setBounds(10, 70, 610, 40);

        txt_nombre.setEditable(false);
        txt_nombre.setBackground(new java.awt.Color(0, 0, 0));
        txt_nombre.setBorder(null);
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        panelCurves1.add(txt_nombre);
        txt_nombre.setBounds(150, 120, 390, 40);

        labelCustom3.setBackground(new java.awt.Color(0, 0, 0));
        labelCustom3.setText("Nombre.");
        panelCurves1.add(labelCustom3);
        labelCustom3.setBounds(20, 120, 130, 40);

        btn_salir.setBackground(new java.awt.Color(0, 51, 0));
        btn_salir.setText("Salir");
        btn_salir.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panelCurves1.add(btn_salir);
        btn_salir.setBounds(490, 490, 116, 30);

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro De Materias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/fondo.jpg"))); // NOI18N
        panel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de Materia.");
        panel1.add(jLabel1);
        jLabel1.setBounds(10, 30, 130, 30);

        txt_nomMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomMateriaActionPerformed(evt);
            }
        });
        panel1.add(txt_nomMateria);
        txt_nomMateria.setBounds(150, 30, 140, 30);

        txt_creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_creditosActionPerformed(evt);
            }
        });
        txt_creditos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_creditosKeyTyped(evt);
            }
        });
        panel1.add(txt_creditos);
        txt_creditos.setBounds(410, 30, 140, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("N° Créditos.");
        panel1.add(jLabel2);
        jLabel2.setBounds(310, 30, 90, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre del Profesor.");
        panel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 130, 30);

        txt_nomProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomProfActionPerformed(evt);
            }
        });
        txt_nomProf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomProfKeyTyped(evt);
            }
        });
        panel1.add(txt_nomProf);
        txt_nomProf.setBounds(150, 90, 140, 30);

        btn_guardar.setBackground(new java.awt.Color(0, 51, 0));
        btn_guardar.setText("Guardar");
        btn_guardar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        panel1.add(btn_guardar);
        btn_guardar.setBounds(250, 160, 116, 30);

        btn_Nuevo1.setBackground(new java.awt.Color(0, 51, 0));
        btn_Nuevo1.setText("Nuevo");
        btn_Nuevo1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_Nuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Nuevo1ActionPerformed(evt);
            }
        });
        panel1.add(btn_Nuevo1);
        btn_Nuevo1.setBounds(390, 160, 116, 30);

        panelCurves1.add(panel1);
        panel1.setBounds(20, 180, 590, 230);

        panelNice1.add(panelCurves1);
        panelCurves1.setBounds(0, 0, 620, 600);

        getContentPane().add(panelNice1);
        panelNice1.setBounds(-6, -2, 620, 600);
        getContentPane().add(panelImage1);
        panelImage1.setBounds(10, 10, 610, 590);

        setSize(new java.awt.Dimension(628, 631));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        guardar();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void tbl_tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tablaMouseClicked
        if (evt.getClickCount()>=2){
            cargarVista();
        }// TODO add your handling code here:
    }//GEN-LAST:event_tbl_tablaMouseClicked

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        cargarVista();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarActionPerformed

    private void txt_nomProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomProfActionPerformed

    private void txt_creditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_creditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_creditosActionPerformed

    private void txt_nomMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomMateriaActionPerformed

    private void btn_Nuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Nuevo1ActionPerformed
        limpiar();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Nuevo1ActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirActionPerformed

    private void txt_nomProfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomProfKeyTyped
        char s = evt.getKeyChar();
            if((s<'a' || s>'z')&&(s<'A' || s>'Z')) evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomProfKeyTyped

    private void txt_creditosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_creditosKeyTyped
        char s = evt.getKeyChar();
            if(s<'0' || s>'9') evt.consume();          // TODO add your handling code here:
    }//GEN-LAST:event_txt_creditosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) ms not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/umswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMRMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMRMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMRMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMRMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and dmsplay the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRMRMaterias dialog = new FRMRMaterias(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonColoredAction btn_Nuevo1;
    private org.edisoncor.gui.button.ButtonColoredAction btn_editar;
    private org.edisoncor.gui.button.ButtonColoredAction btn_guardar;
    private org.edisoncor.gui.button.ButtonColoredAction btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.label.LabelCustom labelCustom1;
    private org.edisoncor.gui.label.LabelCustom labelCustom3;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private javax.swing.JTable tbl_tabla;
    private org.edisoncor.gui.textField.TextFieldRectIcon textFieldRectIcon1;
    private javax.swing.JTextField txt_creditos;
    private javax.swing.JTextField txt_nomMateria;
    private javax.swing.JTextField txt_nomProf;
    private org.edisoncor.gui.textField.TextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
